services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_URLS=http://+:3000

  frontend:
    build: ./public-client
    ports:
      - "4000:80"
    depends_on:
      - api
